apiVersion: v1
kind: ServiceAccount
metadata:
  name: skippy-daemon
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skippy-daemon
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["watch", "get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skippy-daemon
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skippy-daemon
subjects:
- kind: ServiceAccount
  name: skippy-daemon
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: skippy-daemon-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: skippy-daemon
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: skippy-daemon
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: skippy-daemon
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
      - key: node.kubernetes.io/disk-pressure
        effect: NoSchedule
      - key: node.kubernetes.io/memory-pressure
        effect: NoSchedule
      - key: node.kubernetes.io/network-unavailable
        effect: NoSchedule
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
      - key: node.kubernetes.io/unschedulable
        effect: NoSchedule
      containers:
      - image: alexrashed/skippy-daemon:0.6
        name: skippy-daemon
        args: ['-d']
        volumeMounts:
          - name: cuda
            mountPath: /usr/local/cuda
          - name: nvidia-smi-local-bin
            mountPath: /usr/local/bin/nvidia-smi
          - name: nvidia-smi-bin
            mountPath: /usr/bin/nvidia-smi
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
        - name: cuda
          hostPath:
            path: /usr/local/cuda
        - name: nvidia-smi-local-bin
          hostPath:
            path: /usr/local/bin/nvidia-smi
        - name: nvidia-smi-bin
          hostPath:
            path: /usr/bin/nvidia-smi